name: ci-pipeline
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.30
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install required binaries
        run: |
          # install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

          # install k3d
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
      - name: Setup K8s cluster
        run: |
          make k3d-setup
      - name: Run out of cluster integration test
        run: |
          make test-out-of-cluster-setup
          sleep 5
          go test -run TestOutOfCluster ./integration_tests/
      - name: Run in cluster integration test
        run: |
          make image-build
          make test-in-cluster-setup
          go test -run TestInCluster ./integration_tests/
